"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "./components/Navbar/navbar";
import { Provider } from "react-redux";
import store from "../Redux/store";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="main-layout">
          <div className="navbar">
            <Navbar></Navbar>
          </div>
          <div className="page-section">
            <Provider store={store}>{children}</Provider>
          </div>
        </div>
      </body>
    </html>
  );
}
